# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START dev]
# DEV - Cloudbuild build and deploy


steps:

  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "${_IMAGE_NAME}:latest",
      "-t", "${_IMAGE_NAME}:${SHORT_SHA}",
      "--file=cloudbuild/Dockerfile",
      "--cache-from", "${_IMAGE_NAME}:latest",
      "--build-arg", "build_type=${_BUILD_TYPE}",
      "--build-arg", "cloud_project=${PROJECT_ID}",
      "--build-arg", "django_settings=${_DJANGO_SETTINGS}",
      "."]

  - id: "push-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}", "--all-tags"]

  - id: "deploy-cloud-run-service"
    name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "deploy", "${_SERVICE_NAME}",
      "--service-account", "${_SERVICE_ACCOUNT}",
      "--command", "/start",
      "--platform", "managed",
      "--region", "${_REGION}",
      "--image", "${_IMAGE_NAME}:latest",
      "--add-cloudsql-instances", "${_CLOUD_SQL_CONNECTION_NAME}",
      "--allow-unauthenticated",
      "--memory", "2048Mi",
    ]


  - id: "deploy-cloud-run-job-update_index"
    name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "jobs", "deploy", "${_MGMT_CMD_UPDATEINDEX}",
      "--service-account", "${_SERVICE_ACCOUNT}",
      "--region", "${_REGION}",
      "--image", "${_IMAGE_NAME}:latest",
      "--set-cloudsql-instances", "${_CLOUD_SQL_CONNECTION_NAME}",
      "--memory", "1024Mi",
      "--command", "python",
      "--args", "manage.py",
      "--args", "update_index",
    ]
    waitFor: ['push-image']

  - id: "deploy-cloud-run-job-clearsessions"
    name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "jobs", "deploy", "${_MGMT_CMD_CLEARSESSIONS}",
      "--service-account", "${_SERVICE_ACCOUNT}",
      "--region", "${_REGION}",
      "--image", "${_IMAGE_NAME}:latest",
      "--set-cloudsql-instances", "${_CLOUD_SQL_CONNECTION_NAME}",
      "--memory", "1024Mi",
      "--command", "python",
      "--args", "manage.py",
      "--args", "clearsessions",
    ]
    waitFor: ['push-image']


logsBucket: "gs://ccaedu-cloudbuild-log-staging/${_BUILD_TYPE}"

substitutions:
  _BUILD_TYPE: ''  # must define in the build trigger: staging/qa/dev-*
  _DB_INSTANCE_NAME: housegallery
  _DJANGO_SETTINGS: config.settings.production
  _REGION: us-west2
  _SERVICE_ACCOUNT: housegallery-sa
  _SERVICE_NAME: housegallery-${_BUILD_TYPE}-service
  _MGMT_CMD_CLEARSESSIONS: housegallery-${_BUILD_TYPE}-mgmt-cmd-clearsessions
  _MGMT_CMD_UPDATEINDEX: housegallery-${_BUILD_TYPE}-mgmt-cmd-update-index
  _ARTIFACT_REGISTRY: housegallery
  _CLOUD_SQL_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:${_DB_INSTANCE_NAME}
  _IMAGE_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}


options:
  logging: GCS_ONLY
  dynamic_substitutions: true

images:
  - "${_IMAGE_NAME}:latest"
  - "${_IMAGE_NAME}:${SHORT_SHA}"

# [END]
