# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START prod_build]
# PROD - Cloudbuild Build + Backup DB

steps:

  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "${_IMAGE_NAME}:latest",
      "-t", "${_IMAGE_NAME}:${SHORT_SHA}",
      "--file=cloudbuild/Dockerfile",
      "--cache-from", "${_IMAGE_NAME}:latest",
      "--build-arg", "build_type=${_BUILD_TYPE}",
      "--build-arg", "cloud_project=${PROJECT_ID}",
      "--build-arg", "django_settings=${_DJANGO_SETTINGS}",
      "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}", "--all-tags"]

  - id: "backup db"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
      - '-c'  # pass the followings as a command to bash
      - gcloud sql export sql "${_DB_INSTANCE_NAME}" gs://cca-db-exports/"${_DB_NAME}"-$(date +%Y%m%d-%H%M%S).sql.gz --database "${_DB_NAME}"
    waitFor: ['-']  # The '-' indicates that this step begins immediately.
    
  - id: "backup media and static files"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
      - '-c'
      - gcloud storage rsync "gs://${_STORAGE_BUCKET}" "gs://${_STORAGE_BUCKET}-backup" --recursive --delete-unmatched-destination-objects
    waitFor: ['-']
    

logsBucket: "gs://ccaedu-cloudbuild-log-prod/${_BUILD_TYPE}"

substitutions:
  _BUILD_TYPE: prod
  _DB_INSTANCE_NAME: web-instance
  _DB_NAME: ccaedu-${_BUILD_TYPE}
  _DJANGO_SETTINGS: cca.settings.production
  _REGION: us-west2
  _SERVICE_NAME: ccaedu-${_BUILD_TYPE}-service
  _STORAGE_BUCKET: ccaedu-${_BUILD_TYPE}
  _ARTIFACT_REGISTRY: ccaweb
  _IMAGE_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}

options:
  logging: GCS_ONLY
  dynamic_substitutions: true

images:
  - "${_IMAGE_NAME}:latest"
  - "${_IMAGE_NAME}:${SHORT_SHA}"
# [END]
