#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

#exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 config.wsgi:application
