# Generated by Django 5.0.10 on 2025-06-03 04:32

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, help_text='Height x Width x Depth', max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('artifacts', wagtail.fields.StreamField([('image', 2), ('document', 5), ('text', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('document', 3), ('title', 1), ('description', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {})})),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
            },
        ),
        migrations.CreateModel(
            name='ArtworkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='artworks.artwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='artworks.ArtworkTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
