# Generated by Django 5.0.10 on 2025-06-23 05:21

import housegallery.exhibitions.widgets
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artifacts',
            field=wagtail.fields.StreamField([('image', 2), ('document', 5), ('text', 7), ('gallery', 15)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('document', 3), ('title', 1), ('description', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the gallery', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], 'help_text': 'Choose how to display the gallery images'}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable full-width layout using layout gutter spacing', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True, 'widget': housegallery.exhibitions.widgets.ExhibitionImageChooserWidget}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 11), ('caption', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('image', 13)]], {'help_text': 'Add images to the gallery'}), 15: ('wagtail.blocks.StructBlock', [[('title', 8), ('display_style', 9), ('full_width', 10), ('gallery_images', 14)]], {})}),
        ),
    ]
