# Generated by Django 5.0.10 on 2025-06-28 15:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        ('artworks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='artists.artist')),
                ('artwork', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_artists', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Artwork Artist',
                'verbose_name_plural': 'Artwork Artists',
                'unique_together': {('artwork', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='artwork_list', through='artworks.ArtworkArtist', to='artists.artist'),
        ),
    ]
