# Generated by Django 5.0.10 on 2025-04-28 23:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artifacts',
            field=wagtail.fields.StreamField([('image', 2), ('document', 5), ('text', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('document', 3), ('title', 1), ('description', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {})}),
        ),
    ]
