# Generated by Django 5.0.10 on 2025-06-23 05:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artwork_artifacts'),
        ('images', '0007_auto_20250623_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the gallery', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for the gallery')),
                ('display_style', models.CharField(choices=[('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], default='columns', help_text='Choose how to display the gallery images', max_length=50)),
                ('full_width', models.BooleanField(default=False, help_text='Enable full-width layout using layout gutter spacing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artifacts',
            field=wagtail.fields.StreamField([('image', 2), ('document', 5), ('text', 7), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('document', 3), ('title', 1), ('description', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('artworks.Gallery',), {})}),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=255)),
                ('gallery', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='artworks.gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
