# Generated by Django 5.0.10 on 2025-06-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Main cover image for this artwork', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
