# Generated by Django 5.0.10 on 2025-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_artifacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='date_created',
        ),
        migrations.AddField(
            model_name='artwork',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
