# Generated by Django 5.0.10 on 2025-06-28 15:05

from django.db import migrations


def transfer_artist_data(apps, schema_editor):
    """Transfer existing single artist relationships to many-to-many"""
    Artwork = apps.get_model('artworks', 'Artwork')
    ArtworkArtist = apps.get_model('artworks', 'ArtworkArtist')
    
    for artwork in Artwork.objects.filter(artist__isnull=False):
        # Create ArtworkArtist relationship for existing single artist
        ArtworkArtist.objects.get_or_create(
            artwork=artwork,
            artist=artwork.artist,
            defaults={'sort_order': 0}
        )


def reverse_transfer_artist_data(apps, schema_editor):
    """Reverse operation - transfer first artist back to single artist field"""
    Artwork = apps.get_model('artworks', 'Artwork')
    ArtworkArtist = apps.get_model('artworks', 'ArtworkArtist')
    
    for artwork in Artwork.objects.all():
        # Find first artist in the many-to-many relationship
        first_artist_rel = ArtworkArtist.objects.filter(artwork=artwork).order_by('sort_order').first()
        if first_artist_rel:
            artwork.artist = first_artist_rel.artist
            artwork.save()


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artworkartist_artwork_artists'),
    ]

    operations = [
        migrations.RunPython(transfer_artist_data, reverse_transfer_artist_data),
    ]
