# Generated by Django 5.0.10 on 2025-06-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_gallery_alter_artwork_artifacts_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='display_style',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='full_width',
        ),
    ]
