# Generated by Django 5.0.10 on 2025-06-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20250628_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
