# Generated by Django 5.0.10 on 2025-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_modify_artwork_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, help_text='Height x Width x Depth', max_length=255),
        ),
    ]
