# Generated by Django 5.0.10 on 2025-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_remove_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='cover_image',
        ),
    ]
