# Generated by Django 5.0.10 on 2025-06-29 18:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_remove_artwork_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=wagtail.fields.RichTextField(),
        ),
    ]
