# Generated by Django 5.0.10 on 2025-06-29 22:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
