# Generated by Django 5.0.10 on 2025-07-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Artwork Image', 'verbose_name_plural': 'Artwork Images'},
        ),
    ]
