# Generated by Django 5.0.10 on 2025-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_email'),
        ('artworks', '0009_alter_artworkimage_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['-date', 'title'], name='artwork_date_title_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkartist',
            index=models.Index(fields=['artwork', 'artist'], name='artwork_artist_idx'),
        ),
    ]
