# Generated by Django 5.0.10 on 2025-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_artwork_expire_at_artwork_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.CharField(blank=True, help_text='Price or status (e.g., $500, NFS, Sold, Price on request)', max_length=50),
        ),
    ]
