# Generated by Django 5.0.10 on 2026-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_migrate_size_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, help_text="Descriptive size (e.g., 'Dimensions vary', 'Site-specific'). Use dimension fields for numeric values.", max_length=255),
        ),
    ]
