# Generated by Django 5.0.10 on 2026-03-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='preserve_original',
        ),
    ]
