# Generated by Django 5.0.10 on 2025-06-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='preserve_original',
            field=models.BooleanField(default=False, help_text='Keep original file untouched (uses more storage). If unchecked, image will be optimized to high-quality web format. You can reupload the original later if needed.'),
        ),
    ]
