# Generated by Django 5.0.10 on 2025-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_add_preserve_original_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='preserve_original',
            field=models.BooleanField(default=False, help_text='If unchecked, files will be optimized to high-quality web format (recommended for most uploads). Uses more storage when checked.'),
        ),
    ]
