# Generated by Django 5.0.10 on 2025-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_customimagetag_alter_customimage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or additional information about the image'),
        ),
    ]
