# Generated by Django 5.0.10 on 2025-06-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_customimage_description'),
    ]

    operations = [
    ]
