# Generated by Django 5.0.10 on 2025-06-23 07:14

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20250623_0433'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='CustomImageTag',
        ),
    ]
