"""add events model

Revision ID: 6ea769b955ca
Revises: fe8edc047de9
Create Date: 2026-08-09 12:22:15.182422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea769b955ca'
down_revision: Union[str, None] = 'fe8edc047de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('related_exhibition_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('custom_venue_name', sa.String(length=255), nullable=False),
    sa.Column('custom_address', sa.Text(), nullable=False),
    sa.Column('location_details', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=False),
    sa.Column('registration_link', sa.String(length=500), nullable=False),
    sa.Column('ticket_price', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('external_link', sa.String(length=500), nullable=False),
    sa.Column('featured_on_schedule', sa.Boolean(), nullable=False),
    sa.Column('featured_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['featured_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['related_exhibition_id'], ['exhibitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
