"""add home page (hero) model

Revision ID: aa7c8a096f71
Revises: 6ea769b955ca
Create Date: 2026-08-09 16:04:51.982184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7c8a096f71'
down_revision: Union[str, None] = '6ea769b955ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('floating_image_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_page_tenant_id'), 'home_page', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_page_tenant_id'), table_name='home_page')
    op.drop_table('home_page')
    # ### end Alembic commands ###
