#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate
python /app/manage.py collectstatic --noinput --clear --verbosity=0

echo "Static files collected successfully."

exec python manage.py runserver 0.0.0.0:8000
