# Generated by Django 5.0.10 on 2025-06-03 04:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', wagtail.fields.RichTextField(blank=True, help_text="The text summary used when this page appears in listings.                    It's also used as the description for search engines if the                    'Search description' field above is not defined. Max Length: 255", max_length=255, null=True)),
                ('exclude_from_search', models.BooleanField(default=False, help_text='If checked, this page will not appear in site search results')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('button_link', 7), ('list_of_links', 12)], block_lookup={0: ('housegallery.core.blocks.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Rich Text'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text to display. Leave blank to use the page/document title or URL as fallback', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('link_text', 1), ('link_type', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'icon': 'link', 'label': 'Single button'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the list of links', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_text', 1), ('link_type', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Button Style Link'}), 10: ('wagtail.blocks.StructBlock', [[('link_text', 1), ('link_type', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Carrot Style Link'}), 11: ('wagtail.blocks.StreamBlock', [[('button_link', 9), ('carrot_link', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('links', 11)]], {'icon': 'list-ul', 'label': 'List of Links'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='menu', help_text="Title for this list o' links.", max_length=100)),
                ('links', wagtail.fields.StreamField([('normal_link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text to display. Leave blank to use the page/document title or URL as fallback', 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.EmailBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('link_text', 0), ('link_type', 1), ('page', 2), ('external_url', 3), ('document', 4), ('email', 5)]], {}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'CTA links show up in special places (like the header.)', 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Want this link to open in a new tab?', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link', 6), ('is_cta', 7), ('open_in_new_tab', 8)]], {'icon': 'link'})})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
