# Generated by Django 5.0.10 on 2025-04-28 21:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='menu', help_text="Title for this list o' links.", max_length=100)),
                ('links', wagtail.fields.StreamField([('link', 6), ('is_cta', 7), ('open_in_new_tab', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.EmailBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('link_text', 1), ('page', 2), ('external_url', 3), ('document', 4), ('email', 5)]], {}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'CTA links show up in special places (like the header.)', 'required': True}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Want this link to open in a new tab?', 'required': True})})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu', models.ForeignKey(blank=True, help_text='Select the menu to be displayed in the site header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.navigationmenu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
