# Generated by Django 5.0.10 on 2025-04-28 21:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navigationmenu_navigationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='links',
            field=wagtail.fields.StreamField([('normal_link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.EmailBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('link_text', 1), ('page', 2), ('external_url', 3), ('document', 4), ('email', 5)]], {}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'CTA links show up in special places (like the header.)', 'required': True}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Want this link to open in a new tab?', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('link', 6), ('is_cta', 7), ('open_in_new_tab', 8)]], {'icon': 'link'})}),
        ),
    ]
