# Generated by Django 5.0.10 on 2025-05-13 06:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blankpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('button_link', 7), ('list_of_links', 12)], block_lookup={0: ('housegallery.core.blocks.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Rich Text'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'icon': 'link', 'label': 'Single button'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the list of links', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Button Style Link'}), 10: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Carrot Style Link'}), 11: ('wagtail.blocks.StreamBlock', [[('button_link', 9), ('carrot_link', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('links', 11)]], {'icon': 'list-ul', 'label': 'List of Links'})}),
        ),
    ]
