plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Joel\\Code\\personal\\thisisahousegallery\\www\\dist"
publishOrigin = "config"
commandOrigin = "ui"
base = "C:\\Users\\Joel\\Code\\personal\\thisisahousegallery\\www"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]