# Generated by Django 5.0.10 on 2025-04-26 06:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_initial'),
        ('exhibitions', '0001_initial'),
        ('images', '0001_images'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', wagtail.fields.RichTextField(blank=True, help_text="The text summary used when this page appears in listings.                    It's also used as the description for search engines if the                    'Search description' field above is not defined. Max Length: 255", max_length=255, null=True)),
                ('exclude_from_search', models.BooleanField(default=False, help_text='If checked, this page will not appear in site search results')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Exhibition start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Exhibition end date')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitionsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', wagtail.fields.RichTextField(blank=True, help_text="The text summary used when this page appears in listings.                    It's also used as the description for search engines if the                    'Search description' field above is not defined. Max Length: 255", max_length=255, null=True)),
                ('exclude_from_search', models.BooleanField(default=False, help_text='If checked, this page will not appear in site search results')),
                ('body', wagtail.fields.StreamField([('button_link', 6)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.EmailBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('link_type', 0), ('link_text', 1), ('page', 2), ('external_url', 3), ('document', 4), ('email', 5)]], {'icon': 'link', 'label': 'Single button'})})),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitionArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pages', to='artists.artist')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artists', to='exhibitions.exhibitionpage')),
            ],
            options={
                'unique_together': {('page', 'artist')},
            },
        ),
    ]
