# Generated by Django 5.0.10 on 2025-06-25 04:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_initial'),
        ('artworks', '0001_initial'),
        ('exhibitions', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Optional image for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='exhibitionartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pages', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='exhibitionartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pages', to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='exhibitionimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='exhibitionimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_images', to='exhibitions.exhibitionpage'),
        ),
        migrations.AddField(
            model_name='exhibitionartwork',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='exhibitions.exhibitionpage'),
        ),
        migrations.AddField(
            model_name='exhibitionartist',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artists', to='exhibitions.exhibitionpage'),
        ),
        migrations.AddField(
            model_name='exhibitionsindexpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='schedulepage',
            name='featured_events',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select events to display on this schedule page', to='exhibitions.event'),
        ),
        migrations.AddField(
            model_name='schedulepage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
