# Generated by Django 5.0.10 on 2025-06-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
        ('exhibitions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionimage',
            name='related_artwork',
            field=models.ForeignKey(blank=True, help_text='Automatically detected artwork relationship based on image usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_images', to='artworks.artwork'),
        ),
    ]
