# Generated by Django 5.0.10 on 2025-04-30 03:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_artifacts'),
        ('exhibitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitionartist',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitionartist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exhibitionartist',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ExhibitionArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pages', to='artworks.artwork')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='exhibitions.exhibitionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
