# Generated by Django 5.0.10 on 2025-06-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimage',
            name='image_type',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('opening', 'Opening'), ('showcards', 'Showcards')], default='exhibition', help_text='Type of image - exhibition, opening event, or showcards', max_length=20),
        ),
    ]
