# Generated by Django 5.0.10 on 2025-06-22 19:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionpage',
            name='exhibition_images',
            field=wagtail.fields.StreamField([('select_image', 2), ('multiple_images', 3), ('tagged_set', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('housegallery.exhibitions.models.MultipleImagesBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('tag', 4), ('title', 5)]], {})}, help_text="Images from the exhibition - use 'Select Image' for individual images, 'Multiple Images' for bulk selection, or 'Tagged Set' for groups of images by tag"),
        ),
        migrations.AlterField(
            model_name='exhibitionpage',
            name='opening_images',
            field=wagtail.fields.StreamField([('select_image', 2), ('multiple_images', 3), ('tagged_set', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('housegallery.exhibitions.models.MultipleImagesBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('tag', 4), ('title', 5)]], {})}, help_text="Images from the opening event - use 'Select Image' for individual images, 'Multiple Images' for bulk selection, or 'Tagged Set' for groups of images by tag"),
        ),
    ]
