# Generated by Django 5.0.10 on 2025-06-22 20:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_alter_exhibitionpage_exhibition_images_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_gallery_images', to='exhibitions.exhibitionpage')),
            ],
            options={
                'verbose_name': 'Exhibition Gallery Image',
                'verbose_name_plural': 'Exhibition Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='OpeningGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_gallery_images', to='exhibitions.exhibitionpage')),
            ],
            options={
                'verbose_name': 'Opening Gallery Image',
                'verbose_name_plural': 'Opening Gallery Images',
            },
        ),
    ]
