# Generated by Django 5.0.10 on 2025-06-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_exhibitiongalleryimage_openinggalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='exhibition_images',
        ),
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='opening_images',
        ),
    ]
