# Generated by Django 5.0.10 on 2025-07-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_eventpage_eventartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepage',
            name='featured_events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
