# Generated by Django 5.0.10 on 2025-06-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_gallery_alter_artwork_artifacts_galleryimage'),
        ('exhibitions', '0005_remove_exhibitionpage_exhibition_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinggalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='openinggalleryimage',
            name='page',
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='exhibition_gallery',
            field=models.ForeignKey(blank=True, help_text='Select a gallery for exhibition images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_pages', to='artworks.gallery'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='opening_gallery',
            field=models.ForeignKey(blank=True, help_text='Select a gallery for opening event images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_pages', to='artworks.gallery'),
        ),
        migrations.DeleteModel(
            name='ExhibitionGalleryImage',
        ),
        migrations.DeleteModel(
            name='OpeningGalleryImage',
        ),
    ]
