# Generated by Django 5.0.10 on 2025-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0007_alter_exhibitionpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for exhibition video content', null=True),
        ),
    ]
