# Generated by Django 5.0.10 on 2025-05-22 17:59

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0008_schedulepage_scheduleevent'),
        ('images', '0001_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpage',
            name='exhibition_images',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Images from the exhibition', related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='opening_images',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Images from the opening event', related_name='+', to='images.customimage'),
        ),
    ]
