# Generated by Django 5.0.10 on 2025-05-22 18:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0009_exhibitionpage_exhibition_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='exhibition_images',
        ),
        migrations.RemoveField(
            model_name='exhibitionpage',
            name='opening_images',
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='exhibition_images',
            field=wagtail.fields.StreamField([('select_image', 2), ('tagged_set', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter a tag to display all images with this tag', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('tag', 3), ('title', 4)]], {})}, help_text="Images from the exhibition - use 'Select Image' for individual images or 'Tagged Set' for groups of images by tag"),
        ),
        migrations.AddField(
            model_name='exhibitionpage',
            name='opening_images',
            field=wagtail.fields.StreamField([('select_image', 2), ('tagged_set', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter a tag to display all images with this tag', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('tag', 3), ('title', 4)]], {})}, help_text="Images from the opening event - use 'Select Image' for individual images or 'Tagged Set' for groups of images by tag"),
        ),
    ]
