# Generated by Django 5.0.10 on 2025-07-17 20:51

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_artwork_title'),
        ('exhibitions', '0010_alter_exhibitionimage_image_type'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimage',
            name='image_type',
            field=models.CharField(choices=[('exhibition', 'Installation Photos'), ('opening', 'Opening Reception'), ('showcards', 'Showcards'), ('in_progress', 'In Progress Shots')], default='exhibition', help_text='Categorize this image: Installation Photos (gallery setup), Opening Reception (event photos), Showcards (promotional materials), or In Progress Shots (behind-the-scenes)', max_length=20),
        ),
        migrations.CreateModel(
            name='InProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress_photos', to='exhibitions.exhibitionpage')),
            ],
            options={
                'verbose_name': 'In Progress Photo',
                'verbose_name_plural': 'In Progress Photos',
            },
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_photos', to='exhibitions.exhibitionpage')),
                ('related_artwork', models.ForeignKey(blank=True, help_text='Automatically detected artwork relationship based on image usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_photos', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Installation Photo',
                'verbose_name_plural': 'Installation Photos',
            },
        ),
        migrations.CreateModel(
            name='OpeningReceptionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_reception_photos', to='exhibitions.exhibitionpage')),
            ],
            options={
                'verbose_name': 'Opening Reception Photo',
                'verbose_name_plural': 'Opening Reception Photos',
            },
        ),
        migrations.CreateModel(
            name='ShowcardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcard_photos', to='exhibitions.exhibitionpage')),
            ],
            options={
                'verbose_name': 'Showcard Photo',
                'verbose_name_plural': 'Showcard Photos',
            },
        ),
    ]
