# Generated by Django 5.0.10 on 2025-05-22 21:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0010_remove_exhibitionpage_exhibition_images_and_more'),
        ('images', '0001_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('event_type', models.CharField(blank=True, help_text='Type of event (e.g., Exhibition, Residency, Opening)', max_length=255)),
                ('month', models.CharField(help_text='Month of the event (e.g., January, February)', max_length=20)),
                ('year', models.IntegerField(blank=True, help_text='Year of the event (optional)', null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Brief description of the event')),
                ('link', models.URLField(blank=True, help_text='Optional link to more information')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this event from listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Optional image for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-year', 'month', 'title'],
            },
        ),
        migrations.AddField(
            model_name='schedulepage',
            name='featured_events',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select events to display on this schedule page', to='exhibitions.event'),
        ),
    ]
