# Generated by Django 5.0.10 on 2025-07-18 for performance optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0012_auto_20250717_2051'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_start_date ON exhibitions_exhibitionpage (start_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_start_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_end_date ON exhibitions_exhibitionpage (end_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_end_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_dates_composite ON exhibitions_exhibitionpage (start_date, end_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_dates_composite;"
        ),
    ]