# Generated by Django 5.0.10 on 2025-07-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0013_remove_exhibitionpage_featured_image_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_start_date ON exhibitions_exhibitionpage (start_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_start_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_end_date ON exhibitions_exhibitionpage (end_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_end_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_exhibition_dates_composite ON exhibitions_exhibitionpage (start_date, end_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_exhibition_dates_composite;"
        ),
    ]
