# Generated by Django 5.0.10 on 2025-07-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0015_add_typed_image_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcardphoto',
            options={'ordering': ['sort_order'], 'verbose_name': 'Showcard Photo', 'verbose_name_plural': 'Showcard Photos'},
        ),
    ]
