# Generated by Django 5.0.10 on 2025-07-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        ('exhibitions', '0016_alter_showcardphoto_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventartist',
            unique_together={('event', 'artist')},
        ),
        migrations.RemoveField(
            model_name='eventartist',
            name='bio_override',
        ),
        migrations.RemoveField(
            model_name='eventartist',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='eventartist',
            name='role',
        ),
    ]
