# Generated by Django 5.0.10 on 2026-03-12 23:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_alter_artwork_size'),
        ('exhibitions', '0017_alter_eventartist_unique_together_and_more'),
        ('images', '0002_remove_customimage_preserve_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_photos', to='exhibitions.exhibitionpage')),
                ('related_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_photos', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Exhibition Photo',
                'verbose_name_plural': 'Exhibition Photos',
            },
        ),
    ]
