# Generated by Django 5.0.10 on 2025-08-04 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='The API key. Generated automatically if not provided.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable identifier for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is currently active')),
                ('rate_limit', models.PositiveIntegerField(default=1000, help_text='Maximum requests per hour allowed with this key')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses. Empty list allows all IPs.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(help_text='The artist this API key provides access to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='artists.artist')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created'],
            },
        ),
    ]
