# Generated by Django 5.0.10 on 2025-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, db_index=True, help_text='The API key. Generated automatically if not provided.', max_length=64, unique=True),
        ),
    ]
