# Generated by Django 5.0.10 on 2025-07-04 06:05

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the art space or venue', max_length=255)),
                ('start_date', models.DateField(help_text='When this place opened or started operating', verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='When this place closed (leave empty if still operating)', null=True, verbose_name='End date')),
                ('address', models.TextField(help_text='Full address of the place')),
                ('primary_contact', models.CharField(help_text='Person or organization who primarily runs this place', max_length=255)),
                ('primary_link', models.URLField(help_text='Main website or social media link for this place')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Additional details about this place')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this place from listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.customimage')),
                ('place', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='places.place')),
            ],
            options={
                'verbose_name': 'Place Image',
                'verbose_name_plural': 'Place Images',
            },
        ),
    ]
