# Generated by Django 5.0.10 on 2025-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_primary_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the place (optional)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this place opened or started operating (optional)', null=True, verbose_name='Start date'),
        ),
    ]
