# Generated by Django 5.0.10 on 2025-07-04 07:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placesindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesIndexPagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_places', to='places.placesindexpage')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_on_pages', to='places.place')),
            ],
            options={
                'verbose_name': 'Featured Place',
                'verbose_name_plural': 'Featured Places',
                'unique_together': {('page', 'place')},
            },
        ),
    ]
