# Generated by Django 5.0.10 on 2026-03-11 05:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_template', models.CharField(choices=[('split', 'Content with Image(s)'), ('center', 'Single Center Column')], default='split', help_text='Controls the layout and positioning of content', max_length=20)),
                ('display_images', wagtail.fields.StreamField([('gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the gallery', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], 'help_text': 'Choose how to display the gallery images'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable full-width layout using layout gutter spacing', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('tag', 6), ('title', 7)]], {}), 9: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('limit', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('single_image', 5), ('tagged_set', 8), ('all_images', 10)]], {'help_text': 'Add gallery items'}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('display_style', 1), ('full_width', 2), ('gallery_items', 11)]], {'help_text': 'Images for the kiosk display (carousel or static)'})})),
                ('background_style', models.CharField(choices=[('particles', 'Floating Image Particles'), ('static_image', 'Full Screen Photo'), ('solid_color', 'Solid Color')], default='particles', help_text='Controls the visual background behind content', max_length=20)),
                ('background_gallery', wagtail.fields.StreamField([('gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the gallery', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], 'help_text': 'Choose how to display the gallery images'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable full-width layout using layout gutter spacing', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('tag', 6), ('title', 7)]], {}), 9: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('limit', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('single_image', 5), ('tagged_set', 8), ('all_images', 10)]], {'help_text': 'Add gallery items'}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('display_style', 1), ('full_width', 2), ('gallery_items', 11)]], {'help_text': 'Images for the kiosk display (carousel or static)'})}, help_text='Background image(s) (for Full Screen Photo style)')),
                ('background_color', models.CharField(blank=True, default='#111111', help_text='Background color hex code (for Solid Color style)', max_length=7)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('text', 4), ('qr_code', 7), ('mailing_list', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Large (H1)'), ('h2', 'Medium (H2)'), ('h3', 'Small (H3)')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL the QR code links to', 'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]}), 7: ('wagtail.blocks.StructBlock', [[('url', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Stay connected with our gallery', 'help_text': 'Text to encourage mailing list subscription', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'help_text': 'Text for the subscribe button', 'max_length': 50, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('prompt', 8), ('button_text', 9)]], {})})),
                ('max_particles', models.PositiveIntegerField(default=8, help_text='Maximum number of floating particles on screen at once')),
                ('spawn_interval_min', models.PositiveIntegerField(default=1500, help_text='Minimum milliseconds between spawning new particles')),
                ('spawn_interval_max', models.PositiveIntegerField(default=4000, help_text='Maximum milliseconds between spawning new particles')),
            ],
            options={
                'verbose_name': 'Kiosk',
                'verbose_name_plural': 'Kiosks',
            },
            bases=('wagtailcore.page',),
        ),
    ]
