# Generated by Django 5.0.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskpage',
            name='carousel_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Milliseconds between slide transitions'),
        ),
        migrations.AddField(
            model_name='kioskpage',
            name='carousel_transition',
            field=models.CharField(choices=[('crossfade', 'Crossfade'), ('fade-black', 'Fade to Black'), ('zoom-fade', 'Zoom Fade'), ('soft-focus', 'Soft Focus'), ('drift', 'Drift (Ken Burns)')], default='crossfade', help_text='Visual effect used when transitioning between slides', max_length=20),
        ),
        migrations.AddField(
            model_name='kioskpage',
            name='carousel_transition_duration',
            field=models.PositiveIntegerField(default=1200, help_text='Milliseconds for the transition between slides'),
        ),
    ]
