# Generated by Django 5.0.10 on 2026-03-11 22:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_kioskpage_carousel_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskpage',
            name='featured_items',
            field=wagtail.fields.StreamField([('artwork', 1), ('exhibition', 5), ('artist', 7), ('single_image', 10), ('tagged_set', 13), ('all_images', 15)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('artworks.Artwork',), {}), 1: ('wagtail.blocks.StructBlock', [[('artwork', 0)]], {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['exhibitions.ExhibitionPage']}), 3: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Limit the number of images shown (leave blank for all)', 'min_value': 1, 'required': False}), 4: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('exhibition', 'Installation Photos'), ('opening', 'Opening Reception'), ('showcards', 'Showcards'), ('in_progress', 'In Progress Shots'), ('artwork', 'Artwork Images')], 'help_text': 'Which image categories to include (leave blank for all)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('exhibition', 2), ('max_images', 3), ('image_categories', 4)]], {}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('artists.Artist',), {}), 7: ('wagtail.blocks.StructBlock', [[('artist', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('tag', 11), ('title', 12)]], {}), 14: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('limit', 14)]], {})}),
        ),
        migrations.AlterField(
            model_name='kioskpage',
            name='display_template',
            field=models.CharField(choices=[('split', 'Content with Featured Item(s)'), ('center', 'Single Center Column')], default='split', help_text='Controls the layout and positioning of content', max_length=20),
        ),
    ]
