# Generated by Django 5.0.10 on 2026-03-12 20:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_copy_display_images_to_featured_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskpage',
            name='carousel_randomize',
            field=models.BooleanField(default=False, help_text='Shuffle carousel items into a random order on each page load'),
        ),
        migrations.AlterField(
            model_name='kioskpage',
            name='featured_items',
            field=wagtail.fields.StreamField([('artwork', 1), ('exhibition', 5), ('artist', 7), ('all_artwork', 9), ('single_image', 12), ('tagged_set', 15), ('all_images', 17)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('artworks.Artwork',), {}), 1: ('wagtail.blocks.StructBlock', [[('artwork', 0)]], {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['exhibitions.ExhibitionPage']}), 3: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Limit the number of images shown (leave blank for all)', 'min_value': 1, 'required': False}), 4: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('exhibition', 'Installation Photos'), ('opening', 'Opening Reception'), ('showcards', 'Showcards'), ('in_progress', 'In Progress Shots'), ('artwork', 'Artwork Images')], 'help_text': 'Which image categories to include (leave blank for all)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('exhibition', 2), ('max_images', 3), ('image_categories', 4)]], {}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('artists.Artist',), {}), 7: ('wagtail.blocks.StructBlock', [[('artist', 6)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of artworks to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('limit', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('tag', 13), ('title', 14)]], {}), 16: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('limit', 16)]], {})}),
        ),
    ]
