# Generated by Django 5.0.10 on 2025-04-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
    ]
