# Generated by Django 5.0.10 on 2025-04-25 04:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Introduction | Recommended: 10-15 words | Max length: 128 characters.', 'max_length': 128, 'required': True, 'verbose_name': 'Welcome doormatt message'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('link_button', 7), ('link_carrot', 7)]], {'help_text': 'Add some major links bro', 'icon': 'link'}), 9: ('wagtail.blocks.StructBlock', [[('intro', 0), ('ctas', 8)]], {})}),
        ),
    ]
