# Generated by Django 5.0.10 on 2025-05-22 21:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 11), ('gallery', 23)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Introduction | Recommended: 10-15 words | Max length: 128 characters.', 'max_length': 128, 'required': True, 'verbose_name': 'Welcome doormatt message'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom link text. Leave blank to use the page/document title or URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Button Style Link'}), 8: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('link_text', 2), ('page', 3), ('external_url', 4), ('document', 5), ('email', 6)]], {'label': 'Carrot Style Link'}), 9: ('wagtail.blocks.StreamBlock', [[('button_link', 7), ('carrot_link', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('links', 9)]], {'help_text': 'Add links for the hero section', 'label': 'Call to Actions', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('intro', 0), ('ctas', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the gallery', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], 'help_text': 'Choose how to display the gallery images'}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable full-width layout using layout gutter spacing', 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter a tag to display all images with this tag', 'max_length': 100, 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('tag', 18)]], {}), 20: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('limit', 20)]], {}), 22: ('wagtail.blocks.StreamBlock', [[('single_image', 17), ('tagged_set', 19), ('all_images', 21)]], {'help_text': 'Add gallery items'}), 23: ('wagtail.blocks.StructBlock', [[('title', 12), ('display_style', 13), ('full_width', 14), ('gallery_items', 22)]], {})}),
        ),
    ]
