# Generated by Django 5.0.10 on 2026-03-10 01:12

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Marketing medium (e.g., 'Social', 'Print', 'Email', 'Referral').", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campaign Medium',
                'verbose_name_plural': 'Campaign Media',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Traffic source (e.g., 'Instagram', 'Poster', 'Email').", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campaign Source',
                'verbose_name_plural': 'Campaign Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(blank=True, help_text='Email subject line. Defaults to title if blank.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_subject', models.CharField(blank=True, default='', help_text='Subject line for the subscription confirmation email.', max_length=255)),
                ('confirmation_heading', models.CharField(blank=True, default='', help_text='Heading shown in the confirmation email.', max_length=255)),
                ('confirmation_body', models.TextField(blank=True, default='', help_text="Body text for the confirmation email. Use {email} for the subscriber's address.")),
                ('confirmation_button_text', models.CharField(blank=True, default='', help_text='Button text in the confirmation email.', max_length=255)),
                ('unsubscribe_subject', models.CharField(blank=True, default='', help_text='Subject line for the unsubscribe confirmation email.', max_length=255)),
                ('unsubscribe_heading', models.CharField(blank=True, default='', help_text='Heading shown in the unsubscribe email.', max_length=255)),
                ('unsubscribe_body', models.TextField(blank=True, default='', help_text="Body text for the unsubscribe email. Use {email} for the subscriber's address.")),
                ('unsubscribe_button_text', models.CharField(blank=True, default='', help_text='Button text in the unsubscribe email.', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Newsletter Email Settings',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', wagtail.fields.RichTextField(blank=True, help_text="The text summary used when this page appears in listings.                    It's also used as the description for search engines if the                    'Search description' field above is not defined. Max Length: 255", max_length=255, null=True)),
                ('exclude_from_search', models.BooleanField(default=False, help_text='If checked, this page will not appear in site search results')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text above the signup form.')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('gallery', 13), ('button_link', 20), ('list_of_links', 25)], blank=True, block_lookup={0: ('housegallery.core.blocks.content.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Rich Text'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the gallery', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Columns'), ('rows', 'Rows'), ('scattered', 'Scattered')], 'help_text': 'Choose how to display the gallery images'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable full-width layout using layout gutter spacing', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for this image', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter tag name to display all images with this tag', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for this set of images', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('tag', 7), ('title', 8)]], {}), 10: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of images to display (leave blank for all)', 'max_value': 100, 'min_value': 1, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('limit', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('single_image', 6), ('tagged_set', 9), ('all_images', 11)]], {'help_text': 'Add gallery items'}), 13: ('wagtail.blocks.StructBlock', [[('title', 1), ('display_style', 2), ('full_width', 3), ('gallery_items', 12)]], {'icon': 'image', 'label': 'Gallery'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text to display. Leave blank to use the page/document title or URL as fallback', 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('external', 'External URL'), ('document', 'Document'), ('email', 'Email Address')], 'help_text': 'Select the type of link you want to create'}), 16: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.EmailBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('link_text', 14), ('link_type', 15), ('page', 16), ('external_url', 17), ('document', 18), ('email', 19)]], {'icon': 'link', 'label': 'Single button'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the list of links', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('link_text', 14), ('link_type', 15), ('page', 16), ('external_url', 17), ('document', 18), ('email', 19)]], {'label': 'Button Style Link'}), 23: ('wagtail.blocks.StructBlock', [[('link_text', 14), ('link_type', 15), ('page', 16), ('external_url', 17), ('document', 18), ('email', 19)]], {'label': 'Carrot Style Link'}), 24: ('wagtail.blocks.StreamBlock', [[('button_link', 22), ('carrot_link', 23)]], {}), 25: ('wagtail.blocks.StructBlock', [[('title', 21), ('links', 24)]], {'icon': 'list-ul', 'label': 'List of Links'})}, help_text='Additional content below the signup form.')),
                ('campaign_name', models.CharField(blank=True, help_text="UTM campaign name (e.g., 'spring-exhibition-2026').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive pages won't accept new signups.")),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('medium', models.ForeignKey(blank=True, help_text='Marketing medium for this campaign page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.campaignmedium')),
                ('source', models.ForeignKey(blank=True, help_text='Traffic source for this campaign page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.campaignsource')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmed', models.BooleanField(db_index=True, default=False)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bounce_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('signup_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscribers', to='newsletter.newslettersignuppage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
