# Generated by Django 5.0.10 on 2026-03-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='bounce_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
