# Generated by Django 5.0.10 on 2026-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignuppage',
            name='tagline',
            field=models.CharField(blank=True, default='Exhibition openings, events & studio updates.', help_text='Short tagline shown when no intro text is set.', max_length=255),
        ),
        migrations.AddField(
            model_name='newslettersignuppage',
            name='trust_text',
            field=models.CharField(blank=True, default='Monthly updates · No spam · Unsubscribe anytime', help_text='Trust signals shown below the signup form.', max_length=255),
        ),
    ]
