# Generated by Django 5.0.10 on 2026-03-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_add_bounce_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='bounce_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
