# Generated by Django 5.0.10 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettersignuppage_tagline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersignuppage',
            name='tagline',
        ),
    ]
