# Generated by Django 5.0.10 on 2026-03-10 17:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newslettersignuppage_tagline'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('text', 3), ('image_section', 10), ('divider', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('housegallery.newsletter.blocks.EmailTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section heading', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL the image links to', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Text below the image', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'CTA link URL', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'CTA link text', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 4), ('image', 5), ('image_link', 6), ('description', 7), ('link_url', 8), ('link_text', 9)]], {}), 11: ('housegallery.newsletter.blocks.EmailDividerBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='preheader',
            field=models.CharField(blank=True, help_text='Preview text shown in email clients before opening.', max_length=255),
        ),
    ]
