# Generated by Django 5.0.10 on 2026-03-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_add_subscriber_field_indexes'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_subject', models.CharField(blank=True, default='', help_text='Subject line for the subscription confirmation email.', max_length=255)),
                ('confirmation_heading', models.CharField(blank=True, default='', help_text='Heading shown in the confirmation email.', max_length=255)),
                ('confirmation_body', models.TextField(blank=True, default='', help_text="Body text for the confirmation email. Use {email} for the subscriber's address.")),
                ('confirmation_button_text', models.CharField(blank=True, default='', help_text='Button text in the confirmation email.', max_length=255)),
                ('unsubscribe_subject', models.CharField(blank=True, default='', help_text='Subject line for the unsubscribe confirmation email.', max_length=255)),
                ('unsubscribe_heading', models.CharField(blank=True, default='', help_text='Heading shown in the unsubscribe email.', max_length=255)),
                ('unsubscribe_body', models.TextField(blank=True, default='', help_text="Body text for the unsubscribe email. Use {email} for the subscriber's address.")),
                ('unsubscribe_button_text', models.CharField(blank=True, default='', help_text='Button text in the unsubscribe email.', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Newsletter Email Settings',
            },
        ),
    ]
