# Generated by Django 5.0.10 on 2026-03-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_body_newsletter_latest_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscriber Tag',
                'verbose_name_plural': 'Subscriber Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='target_frequency',
            field=models.CharField(blank=True, choices=[('every_issue', 'Every issue'), ('monthly', 'Monthly digest'), ('announcements_only', 'Major announcements only')], help_text='Minimum frequency tier. Leave blank to ignore frequency filtering.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='preferred_frequency',
            field=models.CharField(choices=[('every_issue', 'Every issue'), ('monthly', 'Monthly digest'), ('announcements_only', 'Major announcements only')], default='every_issue', help_text='How often this subscriber wants to receive newsletters.', max_length=20),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='target_tags',
            field=models.ManyToManyField(blank=True, help_text='If set, only subscribers with ANY of these tags receive this newsletter.', related_name='newsletters', to='newsletter.subscribertag'),
        ),
        migrations.AddField(
            model_name='newslettersignuppage',
            name='auto_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags auto-applied to subscribers from this page.', related_name='signup_pages', to='newsletter.subscribertag'),
        ),
        migrations.CreateModel(
            name='SubscriberTagThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.subscriber')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.subscribertag')),
            ],
            options={
                'verbose_name': 'Subscriber Tag Assignment',
                'verbose_name_plural': 'Subscriber Tag Assignments',
                'unique_together': {('subscriber', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='newsletter.SubscriberTagThrough', to='newsletter.subscribertag'),
        ),
    ]
