# Generated by Django 5.0.10 on 2026-03-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletteremailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'March 2026 Poster - Coffee Shop').", max_length=255)),
                ('slug', models.SlugField(help_text='URL identifier used in ?ref= links.', unique=True)),
                ('source', models.CharField(blank=True, help_text="Traffic source (e.g., 'instagram', 'poster', 'personal-email').", max_length=100)),
                ('medium', models.CharField(blank=True, help_text="Marketing medium (e.g., 'social', 'print', 'email', 'referral').", max_length=100)),
                ('campaign_name', models.CharField(blank=True, help_text="Overarching campaign (e.g., 'spring-exhibition-2026').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Notes about where/how this link is used.')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive campaigns won't accept new signups via ref links.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='newsletter.campaign'),
        ),
    ]
