# Generated by Django 5.0.10 on 2026-03-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_segmentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='target_frequency',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='preferred_frequency',
        ),
    ]
