# Generated by Django 5.0.10 on 2025-05-09 06:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='social_media_links',
            field=wagtail.fields.StreamField([('social_link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('vimeo', 'Vimeo'), ('other', 'Other Platform')], 'help_text': 'Select the social media platform'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "If 'Other Platform' is selected, specify the platform name here", 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL to the social media profile', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Username/handle (without the @ symbol)', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('platform', 0), ('platform_name', 1), ('url', 2), ('handle', 3)]], {})}, help_text='Add social media profiles for this artist'),
        ),
    ]
