# Generated by Django 5.0.10 on 2025-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='artist_name_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['birth_year'], name='artist_birth_year_idx'),
        ),
    ]
