# Generated by Django 5.0.10 on 2025-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_artist_name_idx_artist_artist_birth_year_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, help_text="Artist's contact email address", max_length=254),
        ),
    ]
